controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;

class AuthController extends Controller
{

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionSignup()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            return $this->goBack();
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Дальнейшие инструкции отправлены на Ваш email.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Извините, мы не можем отпправить письмо на данный email адрес.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\AuthHandler;
use app\models\Category;
use app\models\City;
use app\models\Country;
use app\models\District;
use app\models\Images;
use app\models\PartnersBanners;
use app\models\Post;
use app\models\PostExtras;
use app\models\search\PostSearch;
use app\models\StaticPage;
use app\models\UploadForm;
use app\models\UploadLogoForm;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use yii\web\HttpException;
use yii\web\Response;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [''],
                'rules' => [
                    // [
                    //     'actions' => ['logout'],
                    //     'allow' => true,
                    //     'roles' => ['@'],
                    // ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {
        (new AuthHandler($client))->handle();
    }

    public function actionRemove() {
        Post::deleteAll(['autor' => 'guest']);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $countUsers = (string)User::find()->count();
        $countPartners = (string)Post::find()->where(['approve' => 1])->count('id');
        for ($i = 0; $i < 9 - strlen($countUsers); $i++) {
            $countUsers = '0' . $countUsers;
        }
        for ($i = 0; $i < 5 - strlen($countPartners); $i++) {
            $countPartners = '0' . $countPartners;
        }
        $regionCookie = isset($_COOKIE['city']) ? urldecode($_COOKIE['city']) : null;
        $region = null;
        if (isset($regionCookie)) {
            $region = City::findOne(['name' => $regionCookie]);
            if (!isset($region)) {
                $region = Country::findOne(['name' => $regionCookie]);
            }
        }
        // var_dump($region);die();

        return $this->render('index', [
            'vipBanners' => PartnersBanners::getVipBanners($region),
            'premiumBanners' => PartnersBanners::getPremiumBanners($region),
            'classicPosts' => Post::getClassicPosts($region, null),
            'standardPosts' => Post::getStandardPosts($region, null, 100),
            'searchModel' => new PostSearch(),
            'categories' => Category::getAllParentCategories(),
            'countClients' => str_split($countUsers),
            'countPartners' => str_split($countPartners),
            'countCities' => str_split((string)City::find()->count('id')),
            //'countries' => Country::getAllWithCities(),
        ]);
    }

    public function actionCountry($country)
    {
        $country = Country::findOne(['name' => $country]);
        $countryId = $country->id - 1;
        return $this->render('list-city', [
            'vipBanners' => PartnersBanners::find()->where(['group' => '90x1000'])->andWhere(['country' => $countryId])->limit(5)->orderBy('id DESC')->all(),
            'premiumBanners' => PartnersBanners::find()->where(['group' => 'premium'])->andWhere(['country' => $countryId])->limit(15)->orderBy('id DESC')->all(),
            'apartmentPosts' => Post::find()->where(['approve' => 1, 'category' => 313])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$country->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'autoPosts' => Post::find()->where(['approve' => 1, 'category' => 312])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$country->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'eatPosts' => Post::find()->where(['approve' => 1, 'category' => 338])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$country->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'classicPosts' => Post::getClassicPosts($country, null),
            'standardPosts' => Post::getStandardPosts($country, null, 100),
            'categories' => Category::getAllParentCategories(),
            'countries' => Country::getAllWithCities(),
            'searchModel' => new PostSearch(),
            'region' => $country->name
        ]);
    }

    public function actionCity($city)
    {
        $city = City::findOne(['name' => $city]);
        $cityId = $city->id - 1;
        return $this->render('list-city', [
            'vipBanners' => PartnersBanners::find()->where(['group' => '90x1000'])->andWhere(['city' => $cityId])->limit(5)->orderBy('id DESC')->all(),
            'premiumBanners' => PartnersBanners::find()->where(['group' => 'premium'])->andWhere(['city' => $cityId])->limit(15)->orderBy('id DESC')->all(),
//            'standardPosts' => Post::find()->where(['approve' => 1])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$city->name.'%', false])->limit(4)->all(),
            'apartmentPosts' => Post::find()->where(['approve' => 1, 'category' => 313])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$city->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'autoPosts' => Post::find()->where(['approve' => 1, 'category' => 312])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$city->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'eatPosts' => Post::find()->where(['approve' => 1, 'category' => 338])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$city->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'categories' => Category::getAllParentCategories(),
            'classicPosts' => Post::getClassicPosts($city, null),
            'standardPosts' => Post::getStandardPosts($city, null, 100),
            'countries' => Country::getAllWithCities(),
            'searchModel' => new PostSearch(),
            'region' => $city->name
        ]);
    }

    public function actionDistrict ($district)
    {
        $district = District::findOne(['name' => $district]);
        $districtId = $district->id - 1;
        return $this->render('list-city', [
            'vipBanners' => PartnersBanners::find()->where(['group' => '90x1000'])->andWhere(['raion' => $districtId])->limit(5)->orderBy('id DESC')->all(),
            'premiumBanners' => PartnersBanners::find()->where(['group' => 'premium'])->andWhere(['raion' => $districtId])->limit(15)->orderBy('id DESC')->all(),
            'standardPosts' => Post::find()->where(['approve' => 1])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$district->name.'%', false])->limit(4)->all(),
            'apartmentPosts' => Post::find()->where(['approve' => 1, 'category' => 313])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$district->name.'%', false])->limit(4)->all(),
            'autoPosts' => Post::find()->where(['approve' => 1, 'category' => 312])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$district->name.'%', false])->limit(4)->all(),
            'eatPosts' => Post::find()->where(['approve' => 1, 'category' => 338])->andWhere(['like', 'xfields', '%top|top1%', false])->andWhere(['like', 'xfields', '%'.$district->name.'%', false])->orderBy('id DESC')->limit(4)->all(),
            'categories' => Category::getAllParentCategories(),
            'countries' => Country::getAllWithCities(),
            'searchModel' => new PostSearch(),
            'region' => $district->name
        ]);
    }

    public function actionCategory($category)
    {
        $regionCookie = isset($_COOKIE['city']) ? urldecode($_COOKIE['city']) : null;
        $region = null;
        if (isset($regionCookie)) {
            $region = City::findOne(['name' => $regionCookie]);
            if (!isset($region)) {
                $region = Country::findOne(['name' => $regionCookie]);
            }
        }
        /** @var Category $currentCategory */
        $currentCategory = Category::find()->with('single')->where(['alt_name' => $category])->one();
        /** @var Category[] $allCategories */
        $allCategories = Category::find()->alias('cat')->where(['cat.alt_name' => $category])->joinWith('parent p')->select('cat.id')->all();
        return $this->render('list', [
            'vipBanners' => PartnersBanners::getVipBanners($region, $currentCategory),
            'premiumBanners' => PartnersBanners::getPremiumBanners($region, $currentCategory),
            'classicPosts' => Post::getClassicPosts($region, $allCategories),
            'standardPosts' => Post::getStandardPosts($region, $allCategories, 100),
            'guestPosts' => Post::getGuestPosts($region, $currentCategory),
            'currentCategory' => $currentCategory,
            'categories' => Category::getAllParentCategories(),
            'countries' => Country::getAllWithCities(),
            'searchModel' => new PostSearch(),
        ]);
    }

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/** @var $this yii\web\View */
/** @var $categories app\models\Category */
/** @var $vipBanners app\models\PartnersBanners */
/** @var $premiumBanners app\models\PartnersBanners */
/** @var $standardPosts app\models\Post title */
/** @var $apartmentPosts app\models\Post */
/** @var $autoPosts app\models\Post */
/** @var $countries app\models\Country */
/** @var $eatPosts app\models\Post */

use yii\helpers\Html;
use yii\helpers\Url;
$this->registerJs(<<< JS
    var container = $('.intro__broadcast');
    var width = container.width();
    container.height(width/4*3);
    container.html('<iframe src="http://demo73.santral.tv/live?w='+width+'&h='+parseInt(width/4*3)+'" frameborder="0" scrolling="no" width="100%" height="100%" allowfullscreen></iframe>')
JS
);

$this->title = 'Дисконтная система';
?>
<!-- PAGE WRAPPER BEGIN -->
<div class="page-wrapper">
    <!-- HEADER BEGIN -->
<!--    <header class="intro">-->
<!--        <nav class="intro-panel">-->
<!--            <div class="container-fluid">-->
<!--                <a href="/" title="Forlife" class="intro-panel__logo">Forlife</a>-->
<!--                <ul class="intro-panel__right">-->
<!--                    <li class="intro-panel__item">-->
<!--                        --><?php //if (Yii::$app->user->isGuest){
//                            echo Html::a('Войти', Url::to('/auth/login'), ['class' => 'intro-panel__link']);
//                        }
//                        else {
//                            echo Html::a('Выйти', Url::to('/auth/logout'), ['class' => 'intro-panel__link']);
//                        }
//                        ?>
<!--                </ul>-->
<!--            </div>-->
<!--        </nav>-->
<!--        <div class="intro__broadcast"></div>-->
<!--        <div class="stats intro-stats">-->
<!--            <div class="stats__widget">-->
<!--                <div class="stats__widget-text">У нас:</div>-->
<!--                --><?php //?>
<!--                <div class="stats__widget-list">-->
<!--                    --><?php //foreach ($countClients as $countClient): ?>
<!--                        <span class="stats__widget-item">--><?//= $countClient ?><!--</span>-->
<!--                    --><?php //endforeach; ?>
<!--                </div>-->
<!--                <div class="stats__widget-text">Потребителей</div>-->
<!--            </div>-->
<!--            <div class="stats__widget">-->
<!--                <div class="stats__widget-text">С нами:</div>-->
<!--                <div class="stats__widget-list">-->
<!--                    --><?php //foreach ($countPartners as $countPartner): ?>
<!--                        <span class="stats__widget-item">--><?//= $countPartner ?><!--</span>-->
<!--                    --><?php //endforeach; ?>
<!--                </div>-->
<!--                <div class="stats__widget-text">Потребителей</div>-->
<!--            </div>-->
<!--            <div class="stats__widget">-->
<!--                <div class="stats__widget-text">Мы в:</div>-->
<!--                <div class="stats__widget-list">-->
<!--                    --><?php //foreach ($countCities as $countCity): ?>
<!--                        <span class="stats__widget-item">--><?//= $countCity ?><!--</span>-->
<!--                    --><?php //endforeach; ?>
<!--                </div>-->
<!--                <div class="stats__widget-text">Регионах</div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </header>-->
    <!--/. HEADER END -->
    <?= \app\widgets\NavbarListWidget::widget([]) ?>
    <?= \app\widgets\NavbarBarWidget::widget([]) ?>
    <?= \app\widgets\BannersWidget::widget(['vipBanners' => $vipBanners, 'premiumBanners' => $premiumBanners]) ?>
    <?= \app\widgets\ClassicListWidget::widget(['classicPosts' => $classicPosts]) ?>
    <?= \app\widgets\StandardListWidget::widget(['standardPosts' => $standardPosts]) ?>
<!--    --><?//= \app\widgets\StandardWidget::widget(['standardPosts' => $standardPosts]) ?>
<!--    --><?//= \app\widgets\FoodsWidget::widget(['foodPosts' => $eatPosts]) ?>
<!--    --><?//= \app\widgets\ApartmentPosts::widget(['apartmentPosts' => $apartmentPosts]) ?>
<!--    --><?//= \app\widgets\CarsWidget::widget(['autoPosts' => $autoPosts]) ?>

    <?= \app\widgets\CategoriesWidget::widget(['categories' => $categories]) ?>

</div>
<!--/. PAGE WRAPPER END -->

<?= \app\widgets\FooterWidget::widget() ?>

views/site/list-city.php
<?php
/** @var $this yii\web\View */
/** @var $categories app\models\Category */
/** @var $vipBanners array app\models\PartnersBanners */
/** @var $premiumBanners array app\models\PartnersBanners */
/** @var $standardPosts array app\models\Post */
/** @var $eatPosts array app\models\Post */
/** @var $apartmentPosts array app\models\Post */
/** @var $autoPosts array app\models\Post */
/** @var $countries array app\models\Country title */
/** @var $this yii\web\View */
use yii\widgets\Breadcrumbs;
use \yii\helpers\Url;

$this->title = $region;
//if (isset($currentCategory->single))
//    $this->params['breadcrumbs'][] = ['label' => $currentCategory->single->name, 'url' => Url::to($currentCategory->alt_name)];
//$this->params['breadcrumbs'][] = ['label' => $this->title];

$totalCount = count($vipBanners)+count($premiumBanners)+count($standardPosts)+count($eatPosts)+count($autoPosts)+count($apartmentPosts);
?>
    <!-- PAGE WRAPPER BEGIN -->
    <div class="page-wrapper">
        <?= \app\widgets\NavbarListWidget::widget([]) ?>
        <!-- MAIN CONTENT BEGIN -->
        <main class="main-content">
            <div class="page-heading">
                <div class="container">
                    <?php // Breadcrumbs::widget([
                        // 'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        // 'options' => ['class' => 'breadcrumbs clearfix']
                    // ]);
                    ?>
                    <h1><?= $region .' ('. $totalCount.')'  ?></h1>
                </div>
            </div>
            <?= \app\widgets\BannersWidget::widget(['vipBanners' => $vipBanners, 'premiumBanners' => $premiumBanners]) ?>
            <?= \app\widgets\ClassicListWidget::widget(['classicPosts' => $classicPosts]) ?>
            <?= \app\widgets\StandardListWidget::widget(['standardPosts' => $standardPosts]) ?>
<!--            --><?//= \app\widgets\StandardWidget::widget(['standardPosts' => $standardPosts]) ?>
<!--            --><?//= \app\widgets\FoodsWidget::widget(['foodPosts' => $eatPosts]) ?>
<!--            --><?//= \app\widgets\ApartmentPosts::widget(['apartmentPosts' => $apartmentPosts]) ?>
<!--            --><?//= \app\widgets\CarsWidget::widget(['autoPosts' => $autoPosts]) ?>
        </main>
        <!--/. MAIN CONTENT END -->
    </div>
    <!--/. PAGE WRAPPER END -->
<?= \app\widgets\FooterWidget::widget() ?>

views/site/list.php
<?php
/** @var $this yii\web\View */
/** @var $categories array app\models\Category */
/** @var $vipBanners array app\models\PartnersBanners */
/** @var $premiumBanners array app\models\PartnersBanners */
/** @var $standardPosts array app\models\Post */
/** @var $classicPosts array app\models\Post */
/** @var $countries array app\models\Country title */
/** @var $currentCategory array app\models\Category */
/** @var $guestPosts array app\models\Category */
/** @var $recommendPosts array app\models\Category */
/** @var $cardPosts array app\models\PartnersBanners */
/** @var $this yii\web\View */
use yii\widgets\Breadcrumbs;
use \yii\helpers\Url;

$this->title = $currentCategory->name;
if (isset($currentCategory->single))
    $this->params['breadcrumbs'][] = ['label' => $currentCategory->single->name, 'url' => Url::to($currentCategory->alt_name)];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => '#', 'class' => 'active'];
$totalCount = count($vipBanners)+count($premiumBanners)+count($standardPosts)+count($classicPosts)+count($guestPosts);
?>
<!-- PAGE WRAPPER BEGIN -->
<div class="page-wrapper">
    <?= \app\widgets\NavbarListWidget::widget([]) ?>
    <!-- MAIN CONTENT BEGIN -->
    <main class="main-content">
        <div class="page-heading">
            <div class="container">
                <?= Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        'options' => ['class' => 'breadcrumbs clearfix']
                    ]);
                ?>
                <h1><?= $currentCategory->name .' ('. $totalCount.')'  ?></h1>
            </div>
        </div>
        <?= \app\widgets\BannersWidget::widget(['vipBanners' => $vipBanners, 'premiumBanners' => $premiumBanners]) ?>
        <?= \app\widgets\ClassicListWidget::widget(['classicPosts' => $classicPosts]) ?>
        <?= \app\widgets\StandardListWidget::widget(['standardPosts' => $standardPosts]) ?>
        <?= \app\widgets\GuestPostsWidget::widget(['guestPosts' => $guestPosts]) ?>
        <?php // echo \app\widgets\RecommendationsWidget::widget(['recommendPosts' => $recommendationPosts]) ?>
        <?php // echo \app\widgets\CardsWidget::widget(['cardBanners' => $cardPosts]) ?>
    </main>
    <!--/. MAIN CONTENT END -->
</div>
<!--/. PAGE WRAPPER END -->
<?= \app\widgets\FooterWidget::widget() ?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/page.php
<?php
/**
 * @var $this yii\web\View
 * @var $page \app\models\StaticPage
 */
$this->title = $page->descr;
?>

<!-- PAGE WRAPPER BEGIN -->
<div class="page-wrapper">
    <?= \app\widgets\NavbarListWidget::widget() ?>

    <div class="margin50"></div>


    <!-- MAIN CONTENT BEGIN -->
    <main class="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <div class="sidebar">
                        <ul id="sidebar-nav">
                            <?php foreach ($allPages as $allPage): ?>
                                <li class="<?= $allPage->name === $page->name ? 'current' : ' ' ?>">
                                    <a href="/page/<?= $allPage->name ?>"><?= $allPage->descr ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="col-md-9 col-sm-9">
                    <div class="contained">
                        <div class="markdown-zone">
                            <?= str_replace('{THEME}', '/templates/forlife', stripslashes($page->template)) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!--/. MAIN CONTENT END -->
    <?= \app\widgets\FooterWidget::widget() ?>
</div>